"""Add rakaat to attendance

Revision ID: 31f57866720d
Revises: 6794af60f30e
Create Date: 2026-02-02 00:20:16.950408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f57866720d'
down_revision = '6794af60f30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taraweeh_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rakaat', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taraweeh_attendance', schema=None) as batch_op:
        batch_op.drop_column('rakaat')

    # ### end Alembic commands ###
