"""Add milestones_seen column to public_user

Revision ID: 410e53364a56
Revises: 503230c0bdc3
Create Date: 2026-02-08 08:10:15.513458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e53364a56'
down_revision = '503230c0bdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestones_seen', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_user', schema=None) as batch_op:
        batch_op.drop_column('milestones_seen')

    # ### end Alembic commands ###
