"""add imam transfer requests and contribution points

Revision ID: e1f96e25b0fb
Revises: 31f57866720d
Create Date: 2026-02-02 23:31:10.410044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f96e25b0fb'
down_revision = '31f57866720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_points', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_user', schema=None) as batch_op:
        batch_op.drop_column('contribution_points')

    # ### end Alembic commands ###
