export { HomePage } from './HomePage'
export { MosqueDetailPage } from './MosqueDetailPage'
export { AboutPage } from './AboutPage'
export { ContactPage } from './ContactPage'
export { NotFoundPage } from './NotFoundPage'
